-- Show warnings after every statement
warnings;

DROP TABLE IF EXISTS BaseFlow;

SELECT 'Create BaseFlow' AS '';

CREATE TABLE BaseFlow (
  id                      INT               NOT NULL AUTO_INCREMENT,
  source_ip               VARCHAR(15)       NOT NULL,
  source_port             DECIMAL(5, 0)     NOT NULL,
  destination_ip          VARCHAR(15)       NOT NULL,
  destination_port        DECIMAL(5, 0)     NOT NULL,
  protocol                DECIMAL(2, 0),
  timestamp               DATETIME,
  duration                DECIMAL(16, 0),
  fwd_packets             DECIMAL(8, 0),
  bwd_packets             DECIMAL(8, 0),
  fwd_packets_bytes       DECIMAL(16, 0),
  bwd_packets_bytes       DECIMAL(16, 0),
  fwd_packets_bytes_max   DECIMAL(8, 0),
  fwd_packets_bytes_min   DECIMAL(8, 0),
  fwd_packets_bytes_mean  DECIMAL(24, 16),
  fwd_packets_bytes_std   DECIMAL(24, 16),
  bwd_packets_bytes_max   DECIMAL(8, 0),
  bwd_packets_bytes_min   DECIMAL(8, 0),
  bwd_packets_bytes_mean  DECIMAL(24, 16),
  bwd_packets_bytes_std   DECIMAL(24, 16),
  bytes_per_second        DECIMAL(32, 16),
  packets_per_second      DECIMAL(32, 16),
  iat_mean                DECIMAL(32, 16),
  iat_std                 DECIMAL(32, 16),
  iat_max                 DECIMAL(16, 0),
  iat_min                 DECIMAL(16, 0),
  fwd_iat_total           DECIMAL(16, 0),
  fwd_iat_mean            DECIMAL(32, 16),
  fwd_iat_std             DECIMAl(32, 16),
  fwd_iat_max             DECIMAL(16, 0),
  fwd_iat_min             DECIMAL(16, 0),
  bwd_iat_total           DECIMAL(16, 0),
  bwd_iat_mean            DECIMAL(32, 16),
  bwd_iat_std             DECIMAl(32, 16),
  bwd_iat_max             DECIMAL(16, 0),
  bwd_iat_min             DECIMAL(16, 0),
  fwd_psh_flags           DECIMAL(2, 0),
  bwd_psh_flags           DECIMAL(2, 0),
  fwd_urg_flags           DECIMAL(2, 0),
  bwd_urg_flags           DECIMAL(2, 0),
  fwd_header_length       DECIMAL(16, 0),
  bwd_header_length       DECIMAL(16, 0),
  fwd_packets_per_second  DECIMAL(40, 24),
  bwd_packets_per_second  DECIMAL(40, 24),
  packet_length_min       DECIMAL(8, 0),
  packet_length_max       DECIMAL(8, 0),
  packet_length_mean      DECIMAL(24, 16),
  packet_length_std       DECIMAL(24, 16),
  packet_length_variance  DECIMAL(32, 16),
  fin_flag_count          DECIMAL(2, 0),
  syn_flag_count          DECIMAL(2, 0),
  rst_flag_count          DECIMAL(2, 0),
  psh_flag_count          DECIMAL(2, 0),
  ack_flag_count          DECIMAL(2, 0),
  urg_flag_count          DECIMAL(2, 0),
  cwe_flag_count          DECIMAL(2, 0),
  ece_flag_count          DECIMAL(2, 0),
  down_up_ratio           DECIMAL(4, 0),
  packet_size_avg         DECIMAL(24, 16),
  fwd_segment_size_avg    DECIMAL(24, 16),
  bwd_segment_size_avg    DECIMAL(24, 16),
  fwd_header_length_1     DECIMAL(16, 0),
  fwd_bytes_bulk_avg      DECIMAL(8, 4),
  fwd_packets_bulk_avg    DECIMAL(8, 4),
  fwd_bulk_rate_avg       DECIMAL(8, 4),
  bwd_bytes_bulk_avg      DECIMAL(8, 4),
  bwd_packets_bulk_avg    DECIMAL(8, 4),
  bwd_bulk_rate_avg       DECIMAL(8, 4),
  fwd_subflow_packets_avg DECIMAL(24, 16),
  fwd_subflow_bytes_avg   DECIMAL(32, 16),
  bwd_subflow_packets_avg DECIMAL(24, 16),
  bwd_subflow_bytes_avg   DECIMAL(32, 16),
  fwd_init_win_bytes      DECIMAL(8, 0),
  bwd_init_win_bytes      DECIMAL(8, 0),
  fwd_act_data_packets    DECIMAL(8, 0),
  fwd_segment_size_min    DECIMAL(8, 0),
  active_time_mean        DECIMAL(32, 16),
  active_time_std         DECIMAL(24, 16),
  active_time_max         DECIMAL(16, 0),
  active_time_min         DECIMAL(16, 0),
  idle_time_mean          DECIMAL(32, 16),
  idle_time_std           DECIMAL(24, 16),
  idle_time_max           DECIMAL(16, 0),
  idle_time_min           DECIMAL(16, 0),
  label                   VARCHAR(32),
  l7_protocol             DECIMAL(4, 0),
  protocol_name           VARCHAR(64),
  PRIMARY KEY (id)
);

LOAD DATA INFILE '/var/lib/mysql-files/Dataset-Unicauca-Version2-87Atts.csv'
INTO TABLE BaseFlow
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
  @ignore1                     ,
  source_ip                    ,
  source_port                  ,
  destination_ip               ,
  destination_port             ,
  protocol                     ,
  @timestamp                   ,
  duration                     ,
  fwd_packets                  ,
  bwd_packets                  ,
  fwd_packets_bytes            ,
  bwd_packets_bytes            ,
  fwd_packets_bytes_max        ,
  fwd_packets_bytes_min        ,
  fwd_packets_bytes_mean       ,
  fwd_packets_bytes_std        ,
  bwd_packets_bytes_max        ,
  bwd_packets_bytes_min        ,
  bwd_packets_bytes_mean       ,
  bwd_packets_bytes_std        ,
  bytes_per_second             ,
  packets_per_second           ,
  iat_mean                     ,
  iat_std                      ,
  iat_max                      ,
  iat_min                      ,
  fwd_iat_total                ,
  fwd_iat_mean                 ,
  fwd_iat_std                  ,
  fwd_iat_max                  ,
  fwd_iat_min                  ,
  bwd_iat_total                ,
  bwd_iat_mean                 ,
  bwd_iat_std                  ,
  bwd_iat_max                  ,
  bwd_iat_min                  ,
  fwd_psh_flags                ,
  bwd_psh_flags                ,
  fwd_urg_flags                ,
  bwd_urg_flags                ,
  fwd_header_length            ,
  bwd_header_length            ,
  fwd_packets_per_second       ,
  bwd_packets_per_second       ,
  packet_length_min            ,
  packet_length_max            ,
  packet_length_mean           ,
  packet_length_std            ,
  packet_length_variance       ,
  fin_flag_count               ,
  syn_flag_count               ,
  rst_flag_count               ,
  psh_flag_count               ,
  ack_flag_count               ,
  urg_flag_count               ,
  cwe_flag_count               ,
  ece_flag_count               ,
  down_up_ratio                ,
  packet_size_avg              ,
  fwd_segment_size_avg         ,
  bwd_segment_size_avg         ,
  fwd_header_length_1          ,
  fwd_bytes_bulk_avg           ,
  fwd_packets_bulk_avg         ,
  fwd_bulk_rate_avg            ,
  bwd_bytes_bulk_avg           ,
  bwd_packets_bulk_avg         ,
  bwd_bulk_rate_avg            ,
  fwd_subflow_packets_avg      ,
  fwd_subflow_bytes_avg        ,
  bwd_subflow_packets_avg      ,
  bwd_subflow_bytes_avg        ,
  fwd_init_win_bytes           ,
  bwd_init_win_bytes           ,
  fwd_act_data_packets         ,
  fwd_segment_size_min         ,
  active_time_mean             ,
  active_time_std              ,
  active_time_max              ,
  active_time_min              ,
  idle_time_mean               ,
  idle_time_std                ,
  idle_time_max                ,
  idle_time_min                ,
  label                        ,
  l7_protocol                  ,
  protocol_name                
)
SET timestamp = STR_TO_DATE(@timestamp, '%d/%m/%Y%T');

-- SELECT COUNT(*) AS 'Row count after loading Dataset-Unicauca-Version2-87Atts.csv' FROM BaseFlow;

LOAD DATA INFILE '/var/lib/mysql-files/Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv'
INTO TABLE BaseFlow
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(
  @ignore1                     ,
  source_ip                    ,
  source_port                  ,
  destination_ip               ,
  destination_port             ,
  protocol                     ,
  @timestamp                   ,
  duration                     ,
  fwd_packets                  ,
  bwd_packets                  ,
  fwd_packets_bytes            ,
  bwd_packets_bytes            ,
  fwd_packets_bytes_max        ,
  fwd_packets_bytes_min        ,
  fwd_packets_bytes_mean       ,
  fwd_packets_bytes_std        ,
  bwd_packets_bytes_max        ,
  bwd_packets_bytes_min        ,
  bwd_packets_bytes_mean       ,
  bwd_packets_bytes_std        ,
  @bytes_per_second            ,
  @packets_per_second          ,
  iat_mean                     ,
  iat_std                      ,
  iat_max                      ,
  iat_min                      ,
  fwd_iat_total                ,
  fwd_iat_mean                 ,
  fwd_iat_std                  ,
  fwd_iat_max                  ,
  fwd_iat_min                  ,
  bwd_iat_total                ,
  bwd_iat_mean                 ,
  bwd_iat_std                  ,
  bwd_iat_max                  ,
  bwd_iat_min                  ,
  fwd_psh_flags                ,
  bwd_psh_flags                ,
  fwd_urg_flags                ,
  bwd_urg_flags                ,
  fwd_header_length            ,
  bwd_header_length            ,
  fwd_packets_per_second       ,
  bwd_packets_per_second       ,
  packet_length_min            ,
  packet_length_max            ,
  packet_length_mean           ,
  packet_length_std            ,
  packet_length_variance       ,
  fin_flag_count               ,
  syn_flag_count               ,
  rst_flag_count               ,
  psh_flag_count               ,
  ack_flag_count               ,
  urg_flag_count               ,
  cwe_flag_count               ,
  ece_flag_count               ,
  down_up_ratio                ,
  packet_size_avg              ,
  fwd_segment_size_avg         ,
  bwd_segment_size_avg         ,
  fwd_header_length_1          ,
  fwd_bytes_bulk_avg           ,
  fwd_packets_bulk_avg         ,
  fwd_bulk_rate_avg            ,
  bwd_bytes_bulk_avg           ,
  bwd_packets_bulk_avg         ,
  bwd_bulk_rate_avg            ,
  fwd_subflow_packets_avg      ,
  fwd_subflow_bytes_avg        ,
  bwd_subflow_packets_avg      ,
  bwd_subflow_bytes_avg        ,
  fwd_init_win_bytes           ,
  bwd_init_win_bytes           ,
  fwd_act_data_packets         ,
  fwd_segment_size_min         ,
  active_time_mean             ,
  active_time_std              ,
  active_time_max              ,
  active_time_min              ,
  idle_time_mean               ,
  idle_time_std                ,
  idle_time_max                ,
  idle_time_min                ,
  label                        ,
  @ignore2                     ,
  @ignore3                
)
SET 
  timestamp = STR_TO_DATE(@timestamp, '%e/%c/%Y %k:%i'),
  bytes_per_second = if (@bytes_per_second REGEXP '\\d', @bytes_per_second, NULL),
  packets_per_second = if (@packets_per_second REGEXP '\\d', @packets_per_second, NULL);

-- SELECT COUNT(*) AS 'Row count after loading Friday-WorkingHours-Afternoon-DDos.pcap_ISCX.csv' FROM BaseFlow;